version: "3"
services:
  ${DB_HOST}:
    container_name: ${DB_HOST}
    image:
      postgres:11-alpine
    ports:
      - 5432:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/postgresql/data
    restart: always

  phaser:
    container_name: phaser
    image: #repository名
      hatnychan/phaser
    build:
      context: .
      dockerfile: Dockerfile_phaser
      args:
        - GIT_USER_NAME=${GIT_USER_NAME}
        - GIT_USER_EMAIL=${GIT_USER_EMAIL}
    ports:
      - "8080:8080"
      - "8000:80"
      - "8022:22"
    tty: #-tに対応
      true
    stdin_open: #-iに対応
      true
    user: #rootとしてログイン(userとしてログインするとsshできない。。。)
      root
    command:
      bash -c "/etc/init.d/ssh start; bash;"
    restart: always
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}