// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface NumParam {
    paramCd: string;
    seq:     number;
    value:   string;
}